image.aspect_ratio         : "1:1",
image.scale                : 1.22,
image.batch_size           : 1,
sampler.base.prompt        : "A detailed iPhone photo. A cute corgi, smiling with great joy, flying high above the river bank in Yosemite National Park, wearing a Superman cape. Bokeh",
sampler.base.negative      : "macrophoto, bokeh, out of focus, draw",
sampler.base.sampler       : "uni_pc",
sampler.base.scheduler     : "simple",
sampler.base.steps         : 12,
sampler.base.steps_start   : 2,
sampler.base.cfg           : 3.4,
sampler.base.noise_seed    : 1,
sampler.refiner.prompt     : "A cute corgi, smiling with great joy, flying high above the river bank in Yosemite National Park, wearing a Superman cape. Bokeh",
sampler.refiner.negative   : "(draw, worst quality, low quality:1.8)",
sampler.refiner.sampler    : "deis",
sampler.refiner.scheduler  : "ddim_uniform",
sampler.refiner.steps      : 11,
sampler.refiner.steps_start: 6,
sampler.refiner.cfg        : 2.0,
sampler.refiner.noise_seed : 1,

